name: Generate documentation for python modules

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Additional Software
      run: |
        sudo apt install python3-sphinx
    - name: Generate Documentation
      run: |
        ./buildscript-documentation.sh
    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: docs
        TARGET_FOLDER: .
