name: Generate documentation for python modules

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate Documentation
      run: |
        ./buildscript-documentation.sh
    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: docs
        TARGET_FOLDER: .
