name: Generate documentation for python modules

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Additional Software
      run: |
        pip install Sphinx


    - name: Generate Documentation
      run: |
        PATH=$PATH:~/.local/bin ./buildscript-documentation.sh

    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: docs
        TARGET_FOLDER: .
